[build]
  command = "yarn build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "20.18.0"

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = """
      default-src 'self';
      script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://ssl.google-analytics.com https://googleads.g.doubleclick.net https://www.googleadservices.com;
      style-src 'self' 'unsafe-inline' https://use.fontawesome.com https://fonts.googleapis.com;
      img-src 'self' data: https: blob:;
      font-src 'self' https://use.fontawesome.com https://fonts.gstatic.com;
      connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://www.googletagmanager.com https://googleads.g.doubleclick.net https://region1.google-analytics.com;
      frame-src 'self' https://www.googletagmanager.com https://td.doubleclick.net;
      object-src 'none';
      base-uri 'self';
      form-action 'self';
    """
